# 1、工作流名称
name: GitHub Actions Build and Deploy

# 2、触发条件为：当master分支有push的时候
on:
  push:
    branches:
      - master

# 3、创建工作流
jobs:
  build-and-deploy:  # 工作流名称
    runs-on: ubuntu-latest  # 依赖环境
    steps:  # 工作流步骤
      # step 1、 获取源码, 拉取仓库代码
      - name: Checkout  # 步骤名
        uses: actions/checkout@master  # 使用插件 => https://github.com/actions/checkout
        with:
          persist-credentials: false

      # step 3、安装依赖并打包
      - name: Install and Build
        run: |
          npm install
          npm run build

      # step 4、部署到指定分支
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.2 # 使用插件 => https://github.com/JamesIves/github-pages-deploy-action
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # 也就是我们刚才生成的 secret
          branch: gh-pages # 部署后提交到的分支
          folder: dist # 这里填打包好的目录名称